version: 1
activeProfile: default
profiles:
  default:
    mode: auto
    budget:
      dailyUSD: 5
      hardStop: true
      warningThreshold: 80
    privacy:
      redactPaths:
        - "**/secrets/**"
        - "**/.env*"
      stripFileContentOverKB: 256
      allowExternal: true
    providers:
      - id: openai
        kind: openai-compat
        baseUrl: https://api.openai.com/v1
        apiKeyRef: OPENAI_API_KEY
        models:
          - name: gpt-4o-mini
            context: 128000
            caps:
              - cheap
              - tools
              - json
            price:
              inputPerMTok: 0.15
              outputPerMTok: 0.6
              cachedInputPerMTok: 0.08
    routing:
      rules:
        - id: default-rule
          if: {}
          then:
            prefer:
              - openai:gpt-4o-mini
            target: chat
      default:
        prefer:
          - openai:gpt-4o-mini
        target: chat
